spring:
  application:
    name: cookeep

  config:
    import: optional:classpath:application-secret.yaml

  jackson:
    time-zone: Asia/Seoul

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Seoul

kakao:
  auth:
    client: ${CLIENT_ID}
    secret: ${CLIENT_SECRET}
    redirect: ${REDIRECT_URI}
    accessTokenURL: https://kauth.kakao.com/oauth/token
    userInfoURL: https://kapi.kakao.com/v2/user/me
jwt:
  access-secret: ${JWT_ACCESS_SECRET_KEY}
  refresh-secret: ${JWT_REFRESH_SECRET_KEY}

google:
  gemini:
    api-key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash
  youtube:
    api-key: ${YOUTUBE_API_KEY}

ai:
  recipe:
    max-change-count: 5

aws:
  s3:
    bucket: ${S3_BUCKET_NAME}
    region: ap-northeast-2
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
logging:
  level:
    org.springframework.security: DEBUG

sms:
  api-key: ${SMS_KEY}
  api-secret: ${SMS_SECRET}
  sender: ${SMS_SENDER}

otp:
  ttl-seconds: 300 # OTP 유효 시간 5분
  send-cooldown-seconds: 60 # 재전송 제한 시간 1분
  max-verify-failures: 5 # 인증 실패 허용 횟수, 초과시 잠금
