-- Seed data for default_ingredients
-- SEED DATA (LOCAL DEV ONLY)
-- This script is executed manually.
-- NOT managed by Flyway.
-- DO NOT run in production DB.
-- DB에서 source "\경로\seed_ingredient.sql;" 입력

INSERT INTO default_ingredients
(category, default_ingredient, default_unit, default_storage, default_expiration_days, ai_tip, image_url)
VALUES
    -- 채소 (VEGETABLE)
    ('VEGETABLE','상추','PIECE','FRIDGE',7,'키친타월로 감싸 밀봉 보관하면 수분이 유지돼요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/5af22114-d81c-4aa5-8914-fae6bfe8a379.svg'),
    ('VEGETABLE','깻잎','PIECE','FRIDGE',7,'세척하지 말고 보관했다가 사용 직전에 씻어주세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','시금치','PIECE','FRIDGE',7,'숨이 잘 죽으니 공기를 최소화해 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','청경채','PIECE','FRIDGE',7,'잎이 눌리지 않게 세워서 보관하면 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png),
    ('VEGETABLE','양배추','PIECE','FRIDGE',7,'겉잎을 제거하지 말고 통째로 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','배추','PIECE','FRIDGE',7,'겉잎이 속을 보호하니 그대로 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','얼갈이','PIECE','FRIDGE',7,'수분이 많아 물기 없이 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','부추','PIECE','FRIDGE',7,'키친타월로 감싸 밀봉하면 향이 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','미나리','PIECE','FRIDGE',7,'줄기가 꺾이지 않도록 세워 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','쑥갓','PIECE','FRIDGE',7,'숨이 빨리 죽어 밀봉 보관이 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','감자','PIECE','FRIDGE',7,'빛을 차단해 싹이 트는 것을 막아주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','고구마','PIECE','FRIDGE',7,'냉기에 약하니 장기 보관은 피해주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','당근','PIECE','FRIDGE',7,'흙을 털고 밀봉하면 수분 유지에 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','무','PIECE','FRIDGE',7,'잎을 제거하고 보관하면 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','마늘','PIECE','FRIDGE',7,'통풍이 중요해 밀봉은 피해주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','양파','PIECE','FRIDGE',7,'껍질을 벗기지 말고 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png),
    ('VEGETABLE','대파','PIECE','FRIDGE',7,'세워서 보관하면 물러지는 것을 막아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','쪽파','PIECE','FRIDGE',7,'키친타월로 감싸 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','마늘쫑','PIECE','FRIDGE',7,'물기 제거 후 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','생강','PIECE','FRIDGE',7,'신문지에 싸서 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','토마토','PIECE','FRIDGE',7,'꼭지를 제거하고 보관하면 신선해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','방울토마토','PIECE','FRIDGE',7,'세척하지 말고 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','오이','PIECE','FRIDGE',7,'수분 손실을 막기 위해 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','애호박','PIECE','FRIDGE',7,'랩으로 감싸 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','가지','PIECE','FRIDGE',7,'저온에 약해 오래 보관은 피하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','파프리카','PIECE','FRIDGE',7,'세척 없이 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','피망','PIECE','FRIDGE',7,'씨를 제거하지 말고 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','단호박','PIECE','FRIDGE',7,'자르지 않은 상태가 가장 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','늙은호박','PIECE','FRIDGE',7,'통째로 보관하는 것이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','브로콜리','PIECE','FRIDGE',7,'물기 제거 후 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','콜리플라워','PIECE','FRIDGE',7,'랩으로 감싸 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','콩나물','PIECE','FRIDGE',7,'밀폐 용기에 담아 빠르게 소비하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','숙주','PIECE','FRIDGE',7,'물기 제거 후 밀봉이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','옥수수','PIECE','FRIDGE',7,'껍질째 보관하면 단맛이 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','아스파라거스','PIECE','FRIDGE',7,'세워서 보관하면 신선해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','샐러리','PIECE','FRIDGE',7,'알루미늄 포일로 감싸 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','양송이버섯','PIECE','FRIDGE',7,'종이봉투에 담아 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','느타리버섯','PIECE','FRIDGE',7,'밀봉은 피하고 통풍이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','새송이버섯','PIECE','FRIDGE',7,'세척 없이 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','팽이버섯','PIECE','FRIDGE',7,'포장 상태 그대로 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','표고버섯','PIECE','FRIDGE',7,'물기 없이 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','고추','PIECE','FRIDGE',7,'랩으로 감싸 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','청양고추','PIECE','FRIDGE',7,'수분 유지가 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','홍고추','PIECE','FRIDGE',7,'세척하지 말고 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','풋고추','PIECE','FRIDGE',7,'밀봉 보관 시 신선도가 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','열무','PIECE','FRIDGE',7,'물기 제거 후 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','시래기','PIECE','FRIDGE',7,'냉장 보관 시 밀봉이 필수예요.'),'https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png',
    ('VEGETABLE','우엉','PIECE','FRIDGE',7,'신문지에 싸 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','연근','PIECE','FRIDGE',7,'물에 담그지 말고 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','비트','PIECE','FRIDGE',7,'껍질째 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','마','PIECE','FRIDGE',7,'절단면은 랩으로 감싸세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','토란','PIECE','FRIDGE',7,'습기 없는 상태로 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','고구마줄기','PIECE','FRIDGE',7,'물기 제거 후 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','케일','PIECE','FRIDGE',7,'키친타월로 감싸 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','로메인','PIECE','FRIDGE',7,'세척하지 말고 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','치커리','PIECE','FRIDGE',7,'공기 차단이 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','양상추','PIECE','FRIDGE',7,'키친타월과 함께 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','적양배추','PIECE','FRIDGE',7,'통째로 보관하면 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','쌈채소믹스','PIECE','FRIDGE',7,'개봉 후 빠르게 소비하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','냉이','PIECE','FRIDGE',7,'물기 제거 후 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','달래','PIECE','FRIDGE',7,'세워서 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','고사리','PIECE','FRIDGE',7,'밀봉 후 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('VEGETABLE','도라지','PIECE','FRIDGE',7,'수분 증발을 막아주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','돌나물','PIECE','FRIDGE',7,'물기 제거 후 밀봉이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('VEGETABLE','명이나물','PIECE','FRIDGE',7,'공기 접촉을 줄여 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/l0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0ettuce.png'),
    ('VEGETABLE','호박잎','PIECE','FRIDGE',7,'키친타월로 감싸 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 과일 (FRUIT)
    ('FRUIT', '사과', 'PIECE', 'FRIDGE', 7, '다른 과일과 함께 두면 빨리 무를 수 있어 따로 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '배', 'PIECE', 'FRIDGE', 7, '수분이 많아 밀봉하면 신선도가 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '바나나', 'PIECE', 'FRIDGE', 7, '꼭지 부분을 랩으로 감싸면 숙성이 느려져요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '귤', 'PIECE', 'FRIDGE', 7, '수분이 차지 않도록 키친타월과 함께 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '오렌지', 'PIECE', 'FRIDGE', 7, '통풍이 되는 곳에 두면 곰팡이를 줄일 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '레몬', 'PIECE', 'FRIDGE', 7, '밀봉 보관하면 향이 오래 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '라임', 'PIECE', 'FRIDGE', 7, '수분이 쉽게 날아가니 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '자몽', 'PIECE', 'FRIDGE', 7, '껍질째 보관하고 잘라둔 건 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '포도', 'PIECE', 'FRIDGE', 7, '씻지 말고 보관했다가 먹기 직전에 씻어주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '청포도', 'PIECE', 'FRIDGE', 7, '물기가 남으면 곰팡이가 생길 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '딸기', 'PIECE', 'FRIDGE', 7, '꼭지를 떼지 말고 보관하면 물러짐이 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '블루베리', 'PIECE', 'FRIDGE', 7, '물 세척은 먹기 직전에 하는 게 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '체리', 'PIECE', 'FRIDGE', 7, '세척하지 말고 밀봉해 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettu0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0ce.png'),
    ('FRUIT', '키위', 'PIECE', 'FRIDGE', 7, '덜 익었다면 실온 숙성 후 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '복숭아', 'PIECE', 'FRIDGE', 7, '덜 익은 건 실온, 완숙은 냉장이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '자두', 'PIECE', 'FRIDGE', 7, '서늘한 곳에서 익힌 뒤 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '감', 'PIECE', 'FRIDGE', 7, '부드러워지기 전 냉장 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '곶감', 'PIECE', 'FRIDGE', 7, '밀봉해 보관하면 건조해지는 걸 막아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '수박', 'PIECE', 'FRIDGE', 7, '자른 수박은 단면을 랩으로 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/lett0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0uce.png'),
    ('FRUIT', '참외', 'PIECE', 'FRIDGE', 7, '향이 강해 밀봉 보관하면 냄새 배임이 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '멜론', 'PIECE', 'FRIDGE', 7, '자르기 전엔 실온, 자른 후엔 밀봉 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/let0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0tuce.png'),
    ('FRUIT', '망고', 'PIECE', 'FRIDGE', 7, '덜 익은 망고는 실온 숙성 후 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '파인애플', 'PIECE', 'FRIDGE', 7, '손질 후 밀봉하면 신선도가 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '아보카도', 'PIECE', 'FRIDGE', 7, '잘라둔 아보카도는 레몬즙을 바르면 갈변이 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '석류', 'PIECE', 'FRIDGE', 7, '알맹이는 밀봉해 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '무화과', 'PIECE', 'FRIDGE', 7, '무르기 쉬우니 빠르게 소비하는 게 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '대추', 'PIECE', 'FRIDGE', 7, '밀봉 보관하면 수분이 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/le0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0ttuce.png'),
    ('FRUIT', '건대추', 'PIECE', 'FRIDGE', 7, '습기를 피해서 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/le0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0ttuce.png'),
    ('FRUIT', '밤', 'PIECE', 'FRIDGE', 7, '수분이 마르지 않게 밀봉 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '은행', 'PIECE', 'FRIDGE', 7, '습기를 피해 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '건포도', 'PIECE', 'FRIDGE', 7, '습기 차단을 위해 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '건망고', 'PIECE', 'FRIDGE', 7, '개봉 후엔 밀봉해 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '건바나나', 'PIECE', 'FRIDGE', 7, '습기를 피하고 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '컵과일', 'PIECE', 'FRIDGE', 7, '개봉 후에는 가능한 빨리 섭취하는 게 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '냉동딸기', 'PIECE', 'FREEZER', 180, '개봉 후엔 공기를 빼서 밀봉하면 성에가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '냉동블루베리', 'PIECE', 'FREEZER', 180, '냉동 보관 시 지퍼백에 공기를 빼고 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '과일잼', 'PIECE', 'FRIDGE', 14, '깨끗한 스푼을 사용하면 오염을 줄일 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '딸기잼', 'PIECE', 'FRIDGE', 14, '사용 후 뚜껑을 바로 닫아 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '블루베리잼', 'PIECE', 'FRIDGE', 14, '수분이 들어가면 곰팡이가 생길 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '사과잼', 'PIECE', 'FRIDGE', 14, '냉장 보관하고, 사용 시 깨끗한 도구를 써주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '귤잼', 'PIECE', 'FRIDGE', 14, '개봉 후 냉장 보관하면 향이 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '망고잼', 'PIECE', 'FRIDGE', 14, '개봉 후에는 항상 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '레몬청', 'PIECE', 'FRIDGE', 14, '수분/이물 혼입을 막고 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '유자', 'PIECE', 'FRIDGE', 7, '밀봉 보관하면 향이 오래 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FRUIT', '유자청', 'PIECE', 'FRIDGE', 14, '깨끗한 도구로 덜어 사용하면 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 육류 (MEAT)
    ('MEAT', '삼겹살', 'PACK', 'FREEZER', 90, '1회분씩 소분해 냉동하면 해동이 편해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '목살', 'PACK', 'FREEZER', 90, '공기를 빼서 밀봉하면 냉동 냄새가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '앞다리살', 'PACK', 'FREEZER', 90, '얇게 펼쳐 냉동하면 빠르게 해동돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '뒷다리살', 'PACK', 'FREEZER', 90, '소분 후 날짜를 적어두면 관리가 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '항정살', 'PACK', 'FREEZER', 90, '기름이 많아 산패를 막기 위해 밀봉이 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '갈매기살', 'PACK', 'FREEZER', 90, '키친타월로 핏물을 닦고 냉동하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '돼지고기다짐육', 'PACK', 'FREEZER', 90, '얇게 눌러 냉동하면 필요한 만큼 떼어 쓰기 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '불고기용소고기', 'PACK', 'FREEZER', 90, '양념 전 소분 냉동하면 활용도가 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '국거리소고기', 'PACK', 'FREEZER', 90, '소분해 냉동하면 해동 시간이 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '등심', 'PACK', 'FREEZER', 90, '랩+지퍼백 이중 포장하면 신선도가 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '안심', 'PACK', 'FREEZER', 90, '공기 접촉을 줄여 냉동 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '부채살', 'PACK', 'FREEZER', 90, '두께를 맞춰 소분하면 조리 시간이 일정해져요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '차돌박이', 'PACK', 'FREEZER', 90, '겹치지 않게 펼쳐 냉동하면 편해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '갈비', 'PACK', 'FREEZER', 90, '핏물 제거 후 냉동하면 잡내가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', 'LA갈비', 'PACK', 'FREEZER', 90, '1회분씩 나눠 냉동하면 해동이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '소고기다짐육', 'PACK', 'FREEZER', 90, '납작하게 냉동하면 빨리 해동돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '양지', 'PACK', 'FREEZER', 90, '소분 후 냉동하면 국물용으로 쓰기 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '사태', 'PACK', 'FREEZER', 90, '결 반대로 썰어 소분 후 냉동하면 편해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭가슴살', 'PACK', 'FREEZER', 90, '개별 포장해 냉동하면 품질이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭다리', 'PACK', 'FREEZER', 90, '핏물 제거 후 냉동하면 냄새가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭봉', 'PACK', 'FREEZER', 90, '한 번에 먹을 양으로 소분해 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭날개', 'PACK', 'FREEZER', 90, '서로 달라붙지 않게 펼쳐 냉동하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '통닭', 'PACK', 'FREEZER', 90, '소분하거나 손질 후 냉동하면 조리가 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭안심', 'PACK', 'FREEZER', 90, '공기를 최대한 빼서 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '훈제오리', 'PACK', 'FREEZER', 90, '개봉 후엔 소분 밀봉 냉동이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '오리고기', 'PACK', 'FREEZER', 90, '기름이 많아 밀봉 냉동이 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '양고기', 'PACK', 'FREEZER', 90, '냉동 전 허브와 함께 밀봉하면 잡내가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '베이컨', 'PACK', 'FREEZER', 90, '한 장씩 떼어지도록 종이를 사이에 끼워 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '햄', 'PACK', 'FREEZER', 90, '개봉 후엔 밀봉해 보관하고 빠르게 소비하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '소시지', 'PACK', 'FREEZER', 90, '개별 포장해 냉동하면 편해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '후랑크소시지', 'PACK', 'FREEZER', 90, '공기를 빼서 밀봉하면 냉동 냄새가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '비엔나소시지', 'PACK', 'FREEZER', 90, '한 번에 쓸 양으로 소분해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '스팸', 'PACK', 'FREEZER', 90, '개봉 후엔 밀봉해 냉장/냉동 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '미트볼', 'PACK', 'FREEZER', 90, '서로 붙지 않게 펼쳐 냉동하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '함박스테이크', 'PACK', 'FREEZER', 90, '냉동 보관 시 공기 접촉을 줄여주세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '떡갈비', 'PACK', 'FREEZER', 90, '포장 상태를 유지하거나 밀봉해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '족발', 'PACK', 'FREEZER', 90, '소분 후 냉동하면 먹을 만큼만 해동할 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '보쌈', 'PACK', 'FREEZER', 90, '기름기 있는 부위는 이중 포장이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '치킨너겟', 'PACK', 'FREEZER', 90, '개봉 후엔 지퍼백 밀봉으로 성에를 줄이세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '치킨스테이크', 'PACK', 'FREEZER', 90, '낱개 포장해 냉동하면 조리가 편해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '돈까스', 'PACK', 'FREEZER', 90, '튀김류는 공기 접촉을 줄이면 눅눅함이 덜해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '불닭', 'PACK', 'FREEZER', 90, '냉동 보관 시 라벨로 날짜를 관리하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '양념닭', 'PACK', 'FREEZER', 90, '양념 육류는 소분 후 냉동하면 활용이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭꼬치', 'PACK', 'FREEZER', 90, '서로 달라붙지 않게 포장해 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '훈제닭가슴살', 'PACK', 'FREEZER', 90, '개봉 후엔 빠르게 소비하고 남은 건 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭가슴살소시지', 'PACK', 'FREEZER', 90, '한 번에 먹을 양으로 소분하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭가슴살볼', 'PACK', 'FREEZER', 90, '냉동 보관 시 공기를 빼서 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '갈비탕용갈비', 'PACK', 'FREEZER', 90, '핏물 제거 후 냉동하면 잡내가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '사골', 'PACK', 'FREEZER', 90, '소분 후 냉동하면 필요한 만큼 쓰기 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '사골육수', 'PACK', 'FREEZER', 90, '냉동 보관 시 평평하게 얼리면 보관이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '곰탕용고기', 'PACK', 'FREEZER', 90, '국물용은 소분 냉동이 가장 편해요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '육포', 'PACK', 'PANTRY', 180, '습기를 피해 밀봉 보관하면 식감이 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '소고기육포', 'PACK', 'PANTRY', 180, '개봉 후엔 밀봉해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '닭육포', 'PACK', 'PANTRY', 180, '습기 유입을 막으면 더 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('MEAT', '캔햄', 'PACK', 'PANTRY', 365, '개봉 후엔 밀봉해 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('MEAT', '베이컨슬라이스', 'PACK', 'FREEZER', 90, '한 장씩 분리해 냉동하면 사용이 편해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('MEAT', '슬라이스햄', 'PACK', 'FREEZER', 90, '겹치지 않게 소분해 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('MEAT', '통햄', 'PACK', 'FREEZER', 90, '자른 후엔 단면을 랩으로 밀봉해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('MEAT', '핫도그', 'PACK', 'FREEZER', 90, '개봉 후 지퍼백 밀봉이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('MEAT', '콘비프', 'PACK', 'PANTRY', 365, '개봉 후엔 냉장 보관하고 빨리 소비하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('MEAT', '양념갈비', 'PACK', 'FREEZER', 90, '양념 고기는 소분 냉동하면 해동이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),

    -- 해산물 (SEAFOOD)
    ('SEAFOOD', '고등어', 'PACK', 'FREEZER', 90, '구입 후 바로 소분 냉동하면 비린내가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '갈치', 'PACK', 'FREEZER', 90, '키친타월로 물기를 제거하고 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '삼치', 'PACK', 'FREEZER', 90, '공기를 빼고 밀봉하면 냉동 냄새가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '꽁치', 'PACK', 'FREEZER', 90, '손질 후 냉동하면 조리가 편해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '조기', 'PACK', 'FREEZER', 90, '비린내 방지를 위해 밀봉 냉동이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '명태', 'PACK', 'FREEZER', 90, '포장 상태를 유지하거나 밀봉해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '동태', 'PACK', 'FREEZER', 90, '한 번에 쓸 만큼 소분해 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '대구', 'PACK', 'FREEZER', 90, '수분을 제거하면 냉동 품질이 좋아져요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '연어', 'PACK', 'FREEZER', 90, '1회분씩 소분해 냉동하면 산화를 줄일 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '참치', 'PACK', 'FREEZER', 90, '해동은 냉장에서 천천히 하는 게 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '참치회', 'PACK', 'FREEZER', 90, '가능하면 빠르게 소비하고 재냉동은 피하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '광어', 'PACK', 'FREEZER', 90, '손질 후 키친타월로 물기 제거가 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '우럭', 'PACK', 'FREEZER', 90, '소분 냉동하면 해동이 편해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '새우', 'PACK', 'FREEZER', 90, '껍질 제거 후 냉동하면 사용이 편해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '칵테일새우', 'PACK', 'FREEZER', 90, '개봉 후 지퍼백 밀봉하면 성에가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '오징어', 'PACK', 'FREEZER', 90, '손질 후 냉동하면 냄새가 덜 배어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '낙지', 'PACK', 'FREEZER', 90, '한 번에 쓸 양으로 소분해 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '쭈꾸미', 'PACK', 'FREEZER', 90, '물기 제거 후 밀봉 냉동이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '문어', 'PACK', 'FREEZER', 90, '삶아서 소분 냉동하면 보관이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '바지락', 'PACK', 'FREEZER', 90, '해감 후 물기 제거하고 냉동하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '홍합', 'PACK', 'FREEZER', 90, '해감 후 소분 냉동하면 편해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '조개', 'PACK', 'FREEZER', 90, '해감 후 냉동하면 보관이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '가리비', 'PACK', 'FREEZER', 90, '손질 후 밀봉 냉동하면 품질이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '전복', 'PACK', 'FREEZER', 90, '손질 후 내장을 분리해 냉동하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '꽃게', 'PACK', 'FREEZER', 90, '비린내 방지를 위해 밀봉이 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '대게', 'PACK', 'FREEZER', 90, '살을 발라 소분 냉동하면 사용이 편해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '게살', 'PACK', 'FREEZER', 90, '평평하게 얼리면 보관이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '어묵', 'PACK', 'FRIDGE', 14, '개봉 후엔 물에 담그지 말고 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '맛살', 'PACK', 'FRIDGE', 14, '개봉 후엔 밀봉해 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '건멸치', 'PACK', 'PANTRY', 180, '습기를 피해 밀봉하면 비린내가 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '국물멸치', 'PACK', 'PANTRY', 180, '냉동 보관하면 산패를 더 줄일 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '다시마', 'PACK', 'PANTRY', 180, '습기 차단이 중요하니 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '미역', 'PACK', 'PANTRY', 180, '건조 상태로 밀봉 보관하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '미역줄기', 'PACK', 'FRIDGE', 14, '개봉 후 밀봉 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '김', 'PACK', 'PANTRY', 180, '습기 차면 눅눅해져 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '조미김', 'PACK', 'PANTRY', 180, '개봉 후엔 밀봉해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '김자반', 'PACK', 'PANTRY', 180, '공기 접촉을 줄이면 바삭함이 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '황태', 'PACK', 'PANTRY', 180, '습기 없는 곳에 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '황태채', 'PACK', 'PANTRY', 180, '개봉 후 밀봉하면 향이 유지돼요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '북어', 'PACK', 'PANTRY', 180, '습기 차단이 중요해요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '북어채', 'PACK', 'PANTRY', 180, '밀봉 보관하면 눅눅함이 줄어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '건새우', 'PACK', 'PANTRY', 180, '냉동 보관하면 산패를 더 줄일 수 있어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '오징어채', 'PACK', 'PANTRY', 180, '습기를 피해 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '쥐포', 'PACK', 'PANTRY', 180, '개봉 후엔 밀봉해 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '어포', 'PACK', 'PANTRY', 180, '습기 유입을 막으면 더 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '어묵탕용어묵', 'PACK', 'FREEZER', 90, '냉동 보관 시 공기 접촉을 줄이세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '어묵꼬치', 'PACK', 'FREEZER', 90, '개봉 후엔 지퍼백 밀봉이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '해물믹스', 'PACK', 'FREEZER', 90, '평평하게 얼리면 보관이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '냉동해물', 'PACK', 'FREEZER', 90, '개봉 후 공기를 빼서 밀봉하면 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '연어스테이크', 'PACK', 'FREEZER', 90, '납작하게 소분 냉동하면 해동이 쉬워요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '생선까스', 'PACK', 'FREEZER', 90, '튀김류는 밀봉해 냉동 냄새를 줄이세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('SEAFOOD', '생선조림용', 'PACK', 'FREEZER', 90, '조림용은 1회분 소분 냉동이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),

    -- 유제품·계란 (DAIRY_EGG)
    ('DAIRY_EGG', '계란', 'PACK', 'FRIDGE', 14, '문 쪽보다 안쪽 칸에 보관하면 온도 변화가 적어요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '우유', 'PACK', 'FRIDGE', 14, '개봉 후엔 뚜껑을 꼭 닫고 빨리 소비하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '두유', 'PACK', 'FRIDGE', 14, '개봉 후엔 냉장 보관하고 빠르게 마셔주세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '요거트', 'PACK', 'FRIDGE', 14, '개봉 후 깨끗한 스푼을 사용하면 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '플레인요거트', 'PACK', 'FRIDGE', 14, '수분/이물 혼입을 피하면 품질이 오래가요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '딸기요거트', 'PACK', 'FRIDGE', 14, '개봉 후엔 가능한 빨리 섭취하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '치즈', 'PACK', 'FRIDGE', 14, '공기 접촉을 줄여 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '슬라이스치즈', 'PACK', 'FRIDGE', 14, '한 장씩 떼어 쓰기 쉽게 그대로 밀봉하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '모짜렐라치즈', 'PACK', 'FRIDGE', 14, '개봉 후엔 밀봉해 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '체다치즈', 'PACK', 'FRIDGE', 14, '건조해지지 않게 밀봉 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '버터', 'PACK', 'FRIDGE', 14, '냄새를 잘 흡수하니 밀봉 보관이 좋아요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '마가린', 'PACK', 'FRIDGE', 14, '개봉 후엔 냉장 보관하고 오염을 피하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '생크림', 'PACK', 'FRIDGE', 14, '개봉 후엔 흔들지 말고 냉장 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '휘핑크림', 'PACK', 'FRIDGE', 14, '개봉 후엔 뚜껑을 꼭 닫아 보관하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),
    ('DAIRY_EGG', '연유', 'PACK', 'FRIDGE', 14, '개봉 후엔 냉장 보관하고 깨끗한 도구를 사용하세요.','https://s3.amazonaws.com/cookeep/ingredients/lettuce.png'),

    -- 곡물·쌀·면 (GRAIN_RICE_NOODLE)
    ('GRAIN_RICE_NOODLE', '쌀', 'BAG', 'PANTRY', 180, '습기 없는 곳에 밀폐 용기로 보관하면 벌레를 줄일 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '즉석밥', 'BAG', 'PANTRY', 180, '직사광선을 피하고 서늘한 곳에 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '컵밥', 'BAG', 'PANTRY', 180, '유통기한이 길어도 고온을 피하면 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '볶음밥', 'BAG', 'FREEZER', 180, '개봉 후 공기를 빼서 밀봉하면 성에가 줄어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '냉동볶음밥', 'BAG', 'FREEZER', 180, '평평하게 눌러 보관하면 공간을 아낄 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '라면', 'BAG', 'PANTRY', 180, '습기와 직사광선을 피하면 면이 덜 눅눅해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '컵라면', 'BAG', 'PANTRY', 180, '상단이 찌그러지지 않게 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '우동', 'BAG', 'FREEZER', 180, '면류는 냉동 보관 시 밀봉이 중요해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '냉동우동', 'BAG', 'FREEZER', 180, '개봉 후엔 지퍼백 밀봉이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '소면', 'BAG', 'PANTRY', 180, '밀봉 보관하면 벌레/습기 유입을 막아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '중면', 'BAG', 'PANTRY', 180, '개봉 후엔 밀봉해서 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '칼국수면', 'BAG', 'FREEZER', 180, '냉동 보관 시 낱개로 분리해 두면 편해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '당면', 'BAG', 'PANTRY', 180, '습기만 피하면 비교적 오래 보관돼요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '쫄면', 'BAG', 'FREEZER', 180, '냉동 보관 시 공기를 빼서 밀봉하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '떡', 'BAG', 'FREEZER', 180, '떡은 냉동 보관하고 필요할 때만 꺼내 쓰세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '떡국떡', 'BAG', 'FREEZER', 180, '서로 달라붙지 않게 펼쳐 냉동하면 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '가래떡', 'BAG', 'FREEZER', 180, '1회분씩 잘라 소분 냉동하면 편해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('GRAIN_RICE_NOODLE', '어묵떡', 'BAG', 'FREEZER', 180, '개봉 후 지퍼백 밀봉 보관이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 빵·베이커리 (BAKERY)
    ('BAKERY', '식빵', 'BAG', 'PANTRY', 5, '빵은 냉동 보관하면 곰팡이를 줄일 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BAKERY', '모닝빵', 'BAG', 'PANTRY', 5, '밀봉하면 수분이 유지돼 촉촉해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BAKERY', '베이글', 'BAG', 'PANTRY', 5, '먹기 좋은 크기로 잘라 냉동하면 편해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BAKERY', '바게트', 'BAG', 'PANTRY', 5, '밀봉 후 냉동 보관하면 바삭함을 되살리기 쉬워요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BAKERY', '크루아상', 'BAG', 'PANTRY', 5, '냉동 후 에어프라이어로 데우면 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BAKERY', '또띠아', 'BAG', 'PANTRY', 5, '한 장씩 분리되게 보관하면 꺼내 쓰기 편해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BAKERY', '피자도우', 'BAG', 'FREEZER', 180, '냉동 도우는 해동을 냉장에서 천천히 하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 양념·소스·조미료 (SEASONING_SAUCE)
    ('SEASONING_SAUCE', '간장', 'BOTTLE', 'PANTRY', 365, '사용 후 뚜껑을 바로 닫아 산화를 줄이세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '된장', 'BOTTLE', 'PANTRY', 365, '깨끗한 스푼을 사용하면 곰팡이를 줄일 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '고추장', 'BOTTLE', 'PANTRY', 365, '수분이 들어가면 변질될 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '쌈장', 'BOTTLE', 'PANTRY', 365, '개봉 후엔 냉장 보관이 더 안전해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '액젓', 'BOTTLE', 'PANTRY', 365, '강한 냄새가 나니 밀봉 보관이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '케첩', 'BOTTLE', 'PANTRY', 365, '개봉 후엔 냉장 보관하면 품질이 유지돼요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '마요네즈', 'BOTTLE', 'PANTRY', 365, '개봉 후엔 반드시 냉장 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '머스타드', 'BOTTLE', 'PANTRY', 365, '개봉 후 냉장 보관하면 풍미가 유지돼요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '굴소스', 'BOTTLE', 'PANTRY', 365, '개봉 후 냉장 보관이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '파스타소스', 'BOTTLE', 'PANTRY', 365, '개봉 후엔 냉장 보관하고 빠르게 소비하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '토마토소스', 'BOTTLE', 'PANTRY', 365, '개봉 후 냉장 보관이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '크림소스', 'BOTTLE', 'PANTRY', 365, '개봉 후엔 반드시 냉장 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '식용유', 'BOTTLE', 'PANTRY', 365, '빛과 열을 피하면 산패를 줄일 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '올리브유', 'BOTTLE', 'PANTRY', 365, '직사광선을 피하고 서늘한 곳에 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '참기름', 'BOTTLE', 'PANTRY', 365, '향이 날아가지 않게 밀봉 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SEASONING_SAUCE', '고추기름', 'BOTTLE', 'PANTRY', 365, '빛을 피하면 색/향이 오래가요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 즉석·간편식 (READY_MEAL)
    ('READY_MEAL', '만두', 'PACK', 'FREEZER', 180, '개봉 후 공기를 빼서 밀봉하면 성에가 줄어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '군만두', 'PACK', 'FREEZER', 180, '서로 달라붙지 않게 보관하면 조리가 편해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '물만두', 'PACK', 'FREEZER', 180, '지퍼백에 밀봉하면 냉동 냄새가 줄어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '비빔만두', 'PACK', 'FREEZER', 180, '한 번에 먹을 양으로 소분해 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '치킨너겟', 'PACK', 'FREEZER', 180, '튀김류는 밀봉이 특히 중요해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '치킨스테이크', 'PACK', 'FREEZER', 180, '낱개로 분리해 냉동하면 꺼내 쓰기 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '함박스테이크', 'PACK', 'FREEZER', 180, '포장 상태를 유지하거나 밀봉해 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '떡갈비', 'PACK', 'FREEZER', 180, '냉동 보관 시 공기 접촉을 줄이세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '냉동피자', 'PACK', 'FREEZER', 180, '개봉 후엔 지퍼백에 넣어 밀봉하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '즉석국', 'PACK', 'FREEZER', 180, '유통기한이 길어도 냉동 온도 유지가 중요해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '즉석찌개', 'PACK', 'FREEZER', 180, '평평하게 얼리면 보관 공간을 줄일 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('READY_MEAL', '즉석카레', 'PACK', 'PANTRY', 180, '직사광선을 피하고 서늘한 곳에 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 과자·스낵·디저트 (SNACK_DESSERT)
    ('SNACK_DESSERT', '감자칩', 'BAG', 'PANTRY', 180, '개봉 후엔 밀봉해 눅눅함을 줄이세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '비스킷', 'BAG', 'PANTRY', 180, '습기를 피하고 밀봉 보관하면 바삭해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '초콜릿', 'BAG', 'PANTRY', 180, '고온을 피하면 하얗게 변하는 현상을 줄일 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '쿠키', 'BAG', 'PANTRY', 180, '밀봉 보관하면 식감이 오래 유지돼요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '젤리', 'BAG', 'PANTRY', 180, '직사광선을 피하면 끈적임이 줄어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '파이', 'BAG', 'PANTRY', 180, '개봉 후엔 밀봉 보관이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '웨하스', 'BAG', 'PANTRY', 180, '습기 차단을 위해 밀봉하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('SNACK_DESSERT', '초코바', 'BAG', 'PANTRY', 180, '더운 곳을 피하면 녹는 걸 막을 수 있어요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 음료 (BEVERAGE)
    ('BEVERAGE', '생수', 'BOTTLE', 'PANTRY', 180, '직사광선을 피하고 서늘한 곳에 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '탄산음료', 'BOTTLE', 'PANTRY', 180, '개봉 후엔 냉장 보관하면 탄산이 오래가요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '이온음료', 'BOTTLE', 'PANTRY', 180, '개봉 후엔 냉장 보관하고 빠르게 마셔주세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '과일주스', 'BOTTLE', 'PANTRY', 180, '개봉 후엔 반드시 냉장 보관하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '커피', 'BOTTLE', 'PANTRY', 180, '개봉 후 냉장 보관하면 맛이 덜 변해요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '캔커피', 'BOTTLE', 'PANTRY', 180, '고온 보관은 피하는 게 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '차음료', 'BOTTLE', 'PANTRY', 180, '개봉 후엔 냉장 보관이 좋아요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('BEVERAGE', '밀크티', 'BOTTLE', 'PANTRY', 180, '개봉 후엔 냉장 보관하고 빠르게 소비하세요.','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),

    -- 절임·발효 (FERMENTED)
    ('FERMENTED', '김치', 'PACK', 'FRIDGE', 90, '김치는 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FERMENTED', '깍두기', 'PACK', 'FRIDGE', 90, '깍두기는 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FERMENTED', '열무김치', 'PACK', 'FRIDGE', 90, '열무김치는 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FERMENTED', '백김치', 'PACK', 'FRIDGE', 90, '백김치는 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FERMENTED', '피클', 'PACK', 'FRIDGE', 90, '피클은 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FERMENTED', '장아찌', 'PACK', 'FRIDGE', 90, '장아찌는 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png'),
    ('FERMENTED', '젓갈', 'PACK', 'FRIDGE', 90, '젓갈은 보관 방법을 잘 지키면 더 오래 신선해요!','https://cookeep-images.s3.ap-northeast-2.amazonaws.com/ingredients/0a0cc3bd-1ade-46ed-897e-ba89ec09b7c0.png');
